/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.gti.asd.ariel.recordkeeping.gui.admin;

import edu.gti.asd.ariel.recordkeeping.model.User;
import edu.gti.asd.ariel.recordkeeping.utils.ContextManager;

/**
 *
 * @author ariel
 */
public class GTIAdminForm extends javax.swing.JFrame {

    private ContextManager contextManager;
    private User user;
    
    /**
     * Creates new form GTIAdminForm
     */
    public GTIAdminForm(ContextManager contextManager, User user) {
        initComponents();
        this.contextManager = contextManager;
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegisterTeacher = new javax.swing.JButton();
        jButtonRegisterStudent = new javax.swing.JButton();
        jButtonReports = new javax.swing.JButton();
        jButtonDepartments = new javax.swing.JButton();
        jButtonCities = new javax.swing.JButton();
        jButtonRegisterStudentInCourse = new javax.swing.JButton();
        jButtonRegisterTeacherInSubject = new javax.swing.JButton();
        jButtonRegisterCourse = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonRegisterUser = new javax.swing.JButton();
        jButtonSubjects = new javax.swing.JButton();
        jButtonSubjectsByCourse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator menu");
        setResizable(false);

        jButtonRegisterTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teacher3.png"))); // NOI18N
        jButtonRegisterTeacher.setToolTipText("Register Teacher");
        jButtonRegisterTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterTeacherActionPerformed(evt);
            }
        });

        jButtonRegisterStudent.setIcon(new javax.swing.ImageIcon("/home/ariel/Desktop/GTI/GTIRecordKeeping/student3.png")); // NOI18N
        jButtonRegisterStudent.setToolTipText("Register Student");
        jButtonRegisterStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterStudentActionPerformed(evt);
            }
        });

        jButtonReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports2.png"))); // NOI18N
        jButtonReports.setToolTipText("Reports / Export Data");

        jButtonDepartments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/department.png"))); // NOI18N
        jButtonDepartments.setToolTipText("Departments");
        jButtonDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepartmentsActionPerformed(evt);
            }
        });

        jButtonCities.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/city.png"))); // NOI18N
        jButtonCities.setToolTipText("Cities / Towns");
        jButtonCities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitiesActionPerformed(evt);
            }
        });

        jButtonRegisterStudentInCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registerStudent.png"))); // NOI18N
        jButtonRegisterStudentInCourse.setToolTipText("Register Student in Course");
        jButtonRegisterStudentInCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterStudentInCourseActionPerformed(evt);
            }
        });

        jButtonRegisterTeacherInSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registerTeacher.png"))); // NOI18N
        jButtonRegisterTeacherInSubject.setToolTipText("Register Teacher in Subject");
        jButtonRegisterTeacherInSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterTeacherInSubjectActionPerformed(evt);
            }
        });

        jButtonRegisterCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/course.png"))); // NOI18N
        jButtonRegisterCourse.setToolTipText("Courses");
        jButtonRegisterCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterCourseActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonRegisterUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jButtonRegisterUser.setToolTipText("Register Users");
        jButtonRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterUserActionPerformed(evt);
            }
        });

        jButtonSubjects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/subject.png"))); // NOI18N
        jButtonSubjects.setToolTipText("Subjects");
        jButtonSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubjectsActionPerformed(evt);
            }
        });

        jButtonSubjectsByCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/subjects_course.png"))); // NOI18N
        jButtonSubjectsByCourse.setToolTipText("Subjects per course");
        jButtonSubjectsByCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubjectsByCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRegisterTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jButtonRegisterTeacherInSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRegisterStudentInCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jButtonRegisterStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRegisterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSubjectsByCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButtonDepartments, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCities, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReports, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jButtonExit)))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRegisterCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButtonCities, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButtonDepartments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRegisterStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButtonRegisterTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRegisterStudentInCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButtonRegisterTeacherInSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRegisterUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButtonSubjectsByCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jButtonExit)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepartmentsActionPerformed
        GTIManageDepartments departmentsForm = new GTIManageDepartments(contextManager);
        departmentsForm.setVisible(true);
    }//GEN-LAST:event_jButtonDepartmentsActionPerformed

    private void jButtonRegisterCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterCourseActionPerformed
        GTIManageCoursesForm coursesForm = new GTIManageCoursesForm(contextManager);
        coursesForm.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterCourseActionPerformed

    private void jButtonRegisterStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterStudentActionPerformed
        GTIRegisterStudentForm studentForm = new GTIRegisterStudentForm(contextManager);
        studentForm.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterStudentActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonCitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitiesActionPerformed
        GTIManageCitiesForm citiesForm = new GTIManageCitiesForm(contextManager);
        citiesForm.setVisible(true);
    }//GEN-LAST:event_jButtonCitiesActionPerformed

    private void jButtonRegisterStudentInCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterStudentInCourseActionPerformed
        GTIRegisterStudentInCourseForm registerStudentInCourse = new GTIRegisterStudentInCourseForm(contextManager);
        registerStudentInCourse.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterStudentInCourseActionPerformed

    private void jButtonRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterUserActionPerformed
        GTIAdminRegisterUserForm userFrom = new GTIAdminRegisterUserForm(contextManager);
        userFrom.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterUserActionPerformed

    private void jButtonRegisterTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterTeacherActionPerformed
        GTIRegisterTeacherForm teacherForm = new GTIRegisterTeacherForm(contextManager);
        teacherForm.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterTeacherActionPerformed

    private void jButtonSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubjectsActionPerformed
        GTIManageSubjects subjectsForm = new GTIManageSubjects(contextManager);
        subjectsForm.setVisible(true);
    }//GEN-LAST:event_jButtonSubjectsActionPerformed

    private void jButtonSubjectsByCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubjectsByCourseActionPerformed
        GTIRegisterSubjectInCourseForm subjectCourseForm = new GTIRegisterSubjectInCourseForm(contextManager);
        subjectCourseForm.setVisible(true);
    }//GEN-LAST:event_jButtonSubjectsByCourseActionPerformed

    private void jButtonRegisterTeacherInSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterTeacherInSubjectActionPerformed
        GTIRegisterTeacherInSubjectForm teacherSubjectForm = new GTIRegisterTeacherInSubjectForm(contextManager);
        teacherSubjectForm.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterTeacherInSubjectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCities;
    private javax.swing.JButton jButtonDepartments;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonRegisterCourse;
    private javax.swing.JButton jButtonRegisterStudent;
    private javax.swing.JButton jButtonRegisterStudentInCourse;
    private javax.swing.JButton jButtonRegisterTeacher;
    private javax.swing.JButton jButtonRegisterTeacherInSubject;
    private javax.swing.JButton jButtonRegisterUser;
    private javax.swing.JButton jButtonReports;
    private javax.swing.JButton jButtonSubjects;
    private javax.swing.JButton jButtonSubjectsByCourse;
    // End of variables declaration//GEN-END:variables

}
