/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.gti.asd.ariel.recordkeeping.gui;

import edu.gti.asd.ariel.recordkeeping.gui.teacher.GTITeachersForm;
import edu.gti.asd.ariel.recordkeeping.gui.admin.GTIAdminForm;
import edu.gti.asd.ariel.recordkeeping.model.User;
import edu.gti.asd.ariel.recordkeeping.service.UserService;
import edu.gti.asd.ariel.recordkeeping.service.UserServiceImpl;
import java.util.Locale;
import java.util.Optional;
import java.util.ResourceBundle;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author ariel
 */
public class GTILoginForm extends javax.swing.JFrame {

    private ClassPathXmlApplicationContext ctx;
    private UserService userService;
    private Logger log = Logger.getLogger(GTILoginForm.class.getName());
    
    
    /**
     * Creates new form GTILoginForm
     */
    public GTILoginForm(ClassPathXmlApplicationContext ctx) {
        this.ctx = ctx;
        initComponents();
        initSpringBeans();
        setLanguage();
        jTextFieldUsername.requestFocus();
    }
    
    private void initSpringBeans() {
        userService = ctx.getBean(UserServiceImpl.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroupLanguage = new javax.swing.ButtonGroup();
        jLabelUser = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jRadioButtonEnglish = new javax.swing.JRadioButton();
        jRadioButtonIrish = new javax.swing.JRadioButton();
        jRadioButtonSpanish = new javax.swing.JRadioButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("edu/gti/asd/ariel/recordkeeping/gui/Bundle"); // NOI18N
        setTitle(bundle.getString("GTILoginForm.title")); // NOI18N
        setResizable(false);

        jLabelUser.setText(bundle.getString("GTILoginForm.jLabelUser.text")); // NOI18N

        jLabelPassword.setText(bundle.getString("GTILoginForm.jLabelPassword.text")); // NOI18N

        jButtonOK.setText(bundle.getString("GTILoginForm.jButtonOK.text")); // NOI18N
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setText(bundle.getString("GTILoginForm.jButtonCancel.text")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gti-logo.png"))); // NOI18N
        jButton1.setFocusable(false);

        buttonGroupLanguage.add(jRadioButtonEnglish);
        jRadioButtonEnglish.setSelected(true);
        jRadioButtonEnglish.setText(bundle.getString("GTILoginForm.jRadioButtonEnglish.text")); // NOI18N
        jRadioButtonEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEnglishActionPerformed(evt);
            }
        });

        buttonGroupLanguage.add(jRadioButtonIrish);
        jRadioButtonIrish.setText(bundle.getString("GTILoginForm.jRadioButtonIrish.text")); // NOI18N
        jRadioButtonIrish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIrishActionPerformed(evt);
            }
        });

        buttonGroupLanguage.add(jRadioButtonSpanish);
        jRadioButtonSpanish.setText(bundle.getString("GTILoginForm.jRadioButtonSpanish.text")); // NOI18N
        jRadioButtonSpanish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSpanishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelUser))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUsername)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonEnglish)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonIrish)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonSpanish)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancel)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUser)
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPassword)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonEnglish)
                            .addComponent(jRadioButtonIrish)
                            .addComponent(jRadioButtonSpanish))
                        .addGap(8, 8, 8))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonCancel))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        String username = jTextFieldUsername.getText();
        String password = String.valueOf(jPasswordField.getPassword());
        
        Optional<User> userOpt = userService.getUserByUsername(username);
        log.info("User from db: " + userOpt.orElse(null));
        
        if (userOpt.isPresent()) {
            User user = userOpt.get();
            if (user.getUsername().equals(username) && user.getPassword().equals(password)) {
                // OK, Check role
                if (user.isAdmin()) {
                    GTIAdminForm adminForm = new GTIAdminForm(ctx, user);
                    adminForm.setVisible(true);
                    dispose();
                } else if (user.isTeacher()) {
                    GTITeachersForm teacherForm = new GTITeachersForm(ctx, user);
                    teacherForm.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Something is wrong with the user... please contact Admin");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Username or password not correct");
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Username " + username + " not found");
        }
        
        
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jRadioButtonEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEnglishActionPerformed
        setLanguage();
    }//GEN-LAST:event_jRadioButtonEnglishActionPerformed

    private void jRadioButtonIrishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIrishActionPerformed
        setLanguage();
    }//GEN-LAST:event_jRadioButtonIrishActionPerformed

    private void jRadioButtonSpanishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSpanishActionPerformed
        setLanguage();
    }//GEN-LAST:event_jRadioButtonSpanishActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GTILoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GTILoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GTILoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GTILoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GTILoginForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupLanguage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JRadioButton jRadioButtonEnglish;
    private javax.swing.JRadioButton jRadioButtonIrish;
    private javax.swing.JRadioButton jRadioButtonSpanish;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    private void setLanguage() {
        Locale locale = null;
        if (jRadioButtonEnglish.isSelected()) {
            locale = new Locale("en", "IE");
        } else if (jRadioButtonIrish.isSelected()) {
            locale = new Locale("ga", "IE");
        } else if (jRadioButtonSpanish.isSelected()) {
            locale = new Locale("es", "ES");
        }
        
        ResourceBundle rb = ResourceBundle.getBundle("edu/gti/asd/ariel/recordkeeping/gui/Bundle", locale);
        
        jLabelUser.setText(rb.getString("GTILoginForm.jLabelUser.text"));
        jLabelPassword.setText(rb.getString("GTILoginForm.jLabelPassword.text"));
        this.setTitle(rb.getString("GTILoginForm.title"));
        jRadioButtonEnglish.setText(rb.getString("GTILoginForm.jRadioButtonEnglish.text"));
        jRadioButtonSpanish.setText(rb.getString("GTILoginForm.jRadioButtonSpanish.text"));
        jRadioButtonIrish.setText(rb.getString("GTILoginForm.jRadioButtonIrish.text"));
        jButtonCancel.setText(rb.getString("GTILoginForm.jButtonCancel.text"));
        jButtonOK.setText(rb.getString("GTILoginForm.jButtonOK.text"));

    }
}
